### ISSUE TITLE
Simulatoin Broken Link

### ISSUE THREAD

**Issue by sravanthimodepu** [openedx-vlead/open-edx-biomedical-instrumentation-lab-iitr#1]
Found simulation broken link in the *Electromyography(EMG) Toolbox* experiment.

![bmi-iitr](https://user-images.githubusercontent.com/11156924/34203866-90bf906c-e5a2-11e7-9b77-c6251366769f.png)

**Comment by madhavipuliraju** [comment]
![screenshot from 2018-01-23 17-30-29](https://user-images.githubusercontent.com/7077897/35274723-325d7b84-0063-11e8-85c2-9f3068f6aca6.png)

**Comment by sravanthimodepu** [comment]
Simulations are working. Hence closing the issue.
