### ISSUE TITLE
Source code is displaying in some experiments

### ISSUE THREAD

**Issue by madhavipuliraju** [openedx-vlead/open-edx-biomedical-instrumentation-lab-iitr#2]
source code is displaying in the following experiments:
1) ECG signal acquisition under incorrect electrode placement 
2) ECG signal acquisition under incorrect electrode placement
3) ECG Acquisition and HRV (Heart Rate variability) analysis in time and frequency domain
4) EEG PSD Calculation 
5) EEG Approximate entropy calculation 
6) EEG Alpha RMS derivation

**Comment by sanchita-dixit** [comment]
The issue was some php error code was visible when experiments were made full screen. Now the issue is resolved.
